version: '3.8'

services:
  web:
    build:
      context: .             # Корень, где лежит Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8012:8012"
    volumes:
      # Монтируем том для хранения БД
      - quiz_data:/app       # Кладём quiz_app.db внутрь /app, как и требуется
    environment:
      - ADMIN_ACCESS_KEY=${ADMIN_ACCESS_KEY_COMPOSE:-SUPER_SECRET_KEY_123_COMPOSE}
    command: uvicorn quiz_app.main:app --host 0.0.0.0 --port 8012

volumes:
  quiz_data:
